/**
 * typeTest.java
 *
 * This file was generated by XMLSpy 2005 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.typeTest;

import com.altova.*;
import com.altova.types.*;
import com.type.*;

public class typeTest {
	protected static void example() throws Exception {
		////////////////////////////////////////////////////////////////////
		//
		// TODO:
		//   Insert your code here...
		//
		// Example code to create and save a structure:
		//   typeDoc doc = new typeDoc();
		//   test_exprType root = new test_exprType();
		//   ...
		//   doc.setRootElementName("", "test_expr");
		//   doc.setSchemaLocation("type.xsd"); // optional
		//   doc.save("type1.xml", root);
		//
		// Example code to load and save a structure:
		//   typeDoc doc = new typeDoc();
		//   test_exprType root = new test_exprType(doc.load("type1.xml"));
		//   ...
		//   doc.save("type1.xml", root);
		//
		////////////////////////////////////////////////////////////////////
	}

	public static void main(String args[]) {
		try {
			System.out.println("type Test Application");
			example();
			System.out.println("OK");
			System.exit(0);
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}
}
