/**
 * TypesNotConvertableException.java
 *
 * This file was generated by XMLSpy 2005 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.altova.types;


public class ValuesNotConvertableException extends SchemaTypeException {
  protected SchemaType object1;
  protected SchemaType object2;

  public ValuesNotConvertableException(SchemaType newobj1, SchemaType newobj2) {
    super("Values could not be converted");
    object1 = newobj1;
    object2 = newobj2;
  }

  public ValuesNotConvertableException(Exception other) {
    super(other);
  }
}
